<Project>
  <Target Name="RemoveMissingCefGlueMacOsCopyItems" BeforeTargets="_CopyOutOfDateSourceItemsToOutputDirectory;_CopyOutOfDateSourceItemsToOutputDirectoryAlways;_CopyResolvedFilesToPublishPreserveNewest;_CopyResolvedFilesToPublishAlways;_CopyResolvedFilesToPublishIfDifferent" Condition="$([MSBuild]::IsOSPlatform('OSX'))">
    <ItemGroup>
      <_SourceItemsToCopyToOutputDirectory Remove="@(_SourceItemsToCopyToOutputDirectory)" Condition="'%(_SourceItemsToCopyToOutputDirectory.Filename)%(_SourceItemsToCopyToOutputDirectory.Extension)' == 'libEGL.dylib' Or '%(_SourceItemsToCopyToOutputDirectory.Filename)%(_SourceItemsToCopyToOutputDirectory.Extension)' == 'libGLESv2.dylib' Or '%(_SourceItemsToCopyToOutputDirectory.Filename)%(_SourceItemsToCopyToOutputDirectory.Extension)' == 'libvk_swiftshader.dylib'" />
      <_SourceItemsToCopyToOutputDirectoryAlways Remove="@(_SourceItemsToCopyToOutputDirectoryAlways)" Condition="'%(_SourceItemsToCopyToOutputDirectoryAlways.Filename)%(_SourceItemsToCopyToOutputDirectoryAlways.Extension)' == 'libEGL.dylib' Or '%(_SourceItemsToCopyToOutputDirectoryAlways.Filename)%(_SourceItemsToCopyToOutputDirectoryAlways.Extension)' == 'libGLESv2.dylib' Or '%(_SourceItemsToCopyToOutputDirectoryAlways.Filename)%(_SourceItemsToCopyToOutputDirectoryAlways.Extension)' == 'libvk_swiftshader.dylib'" />
      <ResolvedFileToPublish Remove="@(ResolvedFileToPublish)" Condition="'%(ResolvedFileToPublish.Filename)%(ResolvedFileToPublish.Extension)' == 'libEGL.dylib' Or '%(ResolvedFileToPublish.Filename)%(ResolvedFileToPublish.Extension)' == 'libGLESv2.dylib' Or '%(ResolvedFileToPublish.Filename)%(ResolvedFileToPublish.Extension)' == 'libvk_swiftshader.dylib'" />
      <_ResolvedFileToPublishPreserveNewest Remove="@(_ResolvedFileToPublishPreserveNewest)" Condition="'%(_ResolvedFileToPublishPreserveNewest.Filename)%(_ResolvedFileToPublishPreserveNewest.Extension)' == 'libEGL.dylib' Or '%(_ResolvedFileToPublishPreserveNewest.Filename)%(_ResolvedFileToPublishPreserveNewest.Extension)' == 'libGLESv2.dylib' Or '%(_ResolvedFileToPublishPreserveNewest.Filename)%(_ResolvedFileToPublishPreserveNewest.Extension)' == 'libvk_swiftshader.dylib'" />
      <_ResolvedFileToPublishAlways Remove="@(_ResolvedFileToPublishAlways)" Condition="'%(_ResolvedFileToPublishAlways.Filename)%(_ResolvedFileToPublishAlways.Extension)' == 'libEGL.dylib' Or '%(_ResolvedFileToPublishAlways.Filename)%(_ResolvedFileToPublishAlways.Extension)' == 'libGLESv2.dylib' Or '%(_ResolvedFileToPublishAlways.Filename)%(_ResolvedFileToPublishAlways.Extension)' == 'libvk_swiftshader.dylib'" />
      <_ResolvedFileToPublishIfDifferent Remove="@(_ResolvedFileToPublishIfDifferent)" Condition="'%(_ResolvedFileToPublishIfDifferent.Filename)%(_ResolvedFileToPublishIfDifferent.Extension)' == 'libEGL.dylib' Or '%(_ResolvedFileToPublishIfDifferent.Filename)%(_ResolvedFileToPublishIfDifferent.Extension)' == 'libGLESv2.dylib' Or '%(_ResolvedFileToPublishIfDifferent.Filename)%(_ResolvedFileToPublishIfDifferent.Extension)' == 'libvk_swiftshader.dylib'" />
    </ItemGroup>
  </Target>
</Project>
